train_file: '../irfl_data/data_split_output/irfl_U_dataset_train.json' 
val_file: '../irfl_data/data_raw/irfl_dataset_test.json'             
test_file: '../irfl_data/data_raw/irfl_dataset_test.json'

image_root: '../irfl_data/data_raw/image_data'

image_res: 384
batch_size_train: 16
batch_size_test: 32

alpha: 0.4
distill: True
warm_up: False

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







