train_file: '../nycartoon_data/data_raw/nycartoon_dataset_train.json' 
val_file: '../nycartoon_data/data_raw/nycartoon_dataset_validation.json'             
test_file: '../nycartoon_data/data_raw/nycartoon_dataset_test.json'

image_root: '../nycartoon_data/data_raw/images'

image_res: 384
batch_size_train: 32
batch_size_test: 64

alpha: 0.4
distill: True
warm_up: False

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}


