train_file: 'sarc_data/text_data/train_filtered.txt'
val_file: 'sarc_data/text_data/valid.txt'                
test_file: 'sarc_data/text_data/test.txt'

image_root: 'sarc_data/image_data'

image_res: 384
batch_size_train: 64
batch_size_test: 128

alpha: 0.4
distill: True
warm_up: False

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







